name: Daily Dutch Tech News

on:
  schedule:
    # This runs at 06:00 UTC every day 
    - cron: '00 6 * * *'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 python-dotenv

      - name: Install Playwright Browsers
        run: python -m playwright install chromium --with-deps

      - name: Run script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python scraper.py